create table records
(
    id       bigint      not null generated by default as identity,
    nickname varchar(20) not null,
    score    smallint    not null,
    datetime timestamp   not null,
    primary key (id)
);